Remove moto<5.0 constraint and update dependencies
edx/api-manager pull request #322
Opened 2024-09-25 11:39 UTC by mfarhan943

**Description:**
Remove moto<5.0 constraint and update dependencies

**Issue Link**
https://github.com/edx/api-manager/issues/276

2024-11-18 10:26 UTC, iamsobanjaved commented
Kindly rebase the PR

2024-12-03 13:10 UTC, UsamaSadiq approved these changes

2024-12-03 13:10 UTC, UsamaSadiq requested changes

2024-12-03 13:10 UTC, UsamaSadiq commented on requirements/base.txt
> +s3transfer==0.10.2
Rebasing needs to be done again to fix the duplicate entries.

2024-12-03 13:58 UTC, UsamaSadiq approved these changes

2024-12-03 13:58 UTC, merged